# -*- coding: utf-8 -*-
"""nn_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C_VbHBPoyN3xYlSGakBeNDSznDFz73Vk
"""

import sys
import os
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# The seed will be fixed to 42 for this assigmnet.
np.random.seed(42)

NUM_FEATS = 90

def relu(z):
  return np.maximum(0,z)

def relu_prime(z):
  return np.where(z > 0, 1.0, 0.0)

class Net(object):
	'''
	'''

	def __init__(self, num_layers, num_units):
		'''
		Initialize the neural network.
		Create weights and biases.
		Here, we have provided an example structure for the weights and biases.
		It is a list of weight and bias matrices, in which, the
		dimensions of weights and biases are (assuming 1 input layer, 2 hidden layers, and 1 output layer):
		weights: [(NUM_FEATS, num_units), (num_units, num_units), (num_units, num_units), (num_units, 1)]
		biases: [(num_units, 1), (num_units, 1), (num_units, 1), (num_units, 1)]
		Please note that this is just an example.
		You are free to modify or entirely ignore this initialization as per your need.
		Also you can add more state-tracking variables that might be useful to compute
		the gradients efficiently.
		Parameters
		----------
			num_layers : Number of HIDDEN layers.
			num_units : Number of units in each Hidden layer.
		'''
		self.num_layers = num_layers
		self.num_units = num_units

		self.biases = []
		self.weights = []
		for i in range(num_layers):
			if i==0:
				# Input layer
				self.weights.append(np.random.uniform(-1, 1, size=(self.num_units, NUM_FEATS)) * np.sqrt(2 / NUM_FEATS))
			else:
				# Hidden layer
				self.weights.append(np.random.uniform(-1, 1, size=(self.num_units, self.num_units)) * np.sqrt(2 / self.num_units))

			self.biases.append(np.random.uniform(-1, 1, size=(self.num_units, 1)) * np.sqrt(2 / self.num_units))

		# Output layer
		self.biases.append(np.random.uniform(-1, 1, size=(1, 1)) * np.sqrt(2 / self.num_units))
		self.weights.append(np.random.uniform(-1, 1, size=(1, self.num_units)) * np.sqrt(2 / self.num_units))

	def __call__(self, X):
		'''
		Forward propagate the input X through the network,
		and return the output.
		Note that for a classification task, the output layer should
		be a softmax layer. So perform the computations accordingly
		Parameters
		----------
			X : Input to the network, numpy array of shape m x d
		Returns
		----------
			y : Output of the network, numpy array of shape m x 1
		'''
		a = X.T
		for i, (w, b) in enumerate(zip(self.weights, self.biases)):
			if i != self.num_layers:
				a = relu(w @ a + b)
			else: a = w @ a + b
		return a 
	
	def backward(self, X, y, lamda):
		'''
		Compute and return gradients loss with respect to weights and biases.
		(dL/dW and dL/db)
		Parameters
		----------
			X : Input to the network, numpy array of shape m x d
			y : Output of the network, numpy array of shape m x 1
			lamda : Regularization parameter.
		Returns
		----------
			del_W : derivative of loss w.r.t. all weight values (a list of matrices).
			del_b : derivative of loss w.r.t. all bias values (a list of vectors).
		Hint: You need to do a forward pass before performing backward pass.
		'''
		batch_size = len(X)
		del_W = [np.zeros(w.shape) for w in self.weights]
		del_b = [np.zeros(b.shape) for b in self.biases]

		activations = [X.T]
		a = X.T
		for i, (w, b) in enumerate(zip(self.weights, self.biases)):
			if(i != self.num_layers): a = relu(w @ a + b)
			else: a = w @ a + b
			activations.append(a)
		
		delta = activations[-1] - [y]
		del_b[-1] = (1./batch_size) * np.sum(delta, axis = 1, keepdims = True)
		del_W[-1] = (1./batch_size) * ((delta @ activations[-2].T) + lamda * self.weights[-1])

		for i in range(2, self.num_layers + 2):
			delta = (self.weights[-i + 1].T @ delta) * relu_prime(activations[-i])
			del_b[-i] = (1./batch_size) * np.sum(delta, axis = 1, keepdims = True)
			del_W[-i] = (1./batch_size) * ((delta @ activations[-i - 1].T) + lamda * self.weights[-i])

		return del_W, del_b

class Optimizer(object):
	'''
	'''
	def __init__(self, learning_rate, weights, biases):
		'''
		Create a Gradient Descent based optimizer with given
		learning rate.
		Other parameters can also be passed to create different types of
		optimizers.
		Hint: You can use the class members to track various states of the
		optimizer.
		'''
		self.m_dw = [np.zeros(w.shape) for w in weights]
		self.m_db = [np.zeros(b.shape) for b in biases]
		self.v_dw = [np.zeros(w.shape) for w in weights]
		self.v_db = [np.zeros(b.shape) for b in biases]
		self.beta1 = 0.9
		self.beta2 = 0.999
		self.epsilon = 1e-8
		self.eta = learning_rate
		self.t = 0

	def step(self, weights, biases, delta_weights, delta_biases):
		'''
		Parameters
		----------
			weights: Current weights of the network.
			biases: Current biases of the network.
			delta_weights: Gradients of weights with respect to loss.
			delta_biases: Gradients of biases with respect to loss.
		'''
		self.t += 1

		self.m_dw = [self.beta1 * m + (1 - self.beta1) * del_w for m, del_w in zip(self.m_dw, delta_weights)]
		self.m_db = [self.beta1 * m + (1 - self.beta1) * del_b for m, del_b in zip(self.m_db, delta_biases)]
		self.v_dw = [self.beta2 * v + (1 - self.beta2) * (del_w**2) for v, del_w in zip(self.v_dw, delta_weights)]
		self.v_db = [self.beta2 * v + (1 - self.beta2) * (del_b**2) for v, del_b in zip(self.v_db, delta_biases)]

		# bias correction
		m_hat_dw = [m / (1 - self.beta1 ** self.t) for m in self.m_dw]
		m_hat_db = [m / (1 - self.beta1 ** self.t) for m in self.m_db]
		v_hat_dw = [v / (1 - self.beta2 ** self.t) for v in self.v_dw]
		v_hat_db = [v / (1 - self.beta2 ** self.t) for v in self.v_db]
	
		# update weights and biases
		weights = [w - self.eta * (m_hat / (np.sqrt(v_hat) + self.epsilon)) for w, m_hat, v_hat in zip(weights, m_hat_dw, v_hat_dw)] 
		biases = [b - self.eta * (m_hat / (np.sqrt(v_hat) + self.epsilon)) for b, m_hat, v_hat in zip(biases, m_hat_db, v_hat_db)]

		return weights, biases

def loss_mse(y, y_hat):
	'''
	Compute Mean Squared Error (MSE) loss between ground-truth and predicted values.
	Parameters
	----------
		y : targets, numpy array of shape m x 1
		y_hat : predictions, numpy array of shape m x 1
	Returns
	----------
		MSE loss between y and y_hat.
	'''
	return ((y - y_hat)**2).mean()

def loss_regularization(weights, biases):
	'''
	Compute l2 regularization loss.
	Parameters
	----------
		weights and biases of the network.
	Returns
	----------
		l2 regularization loss 
	'''
	return np.sum([np.linalg.norm(w) for w in weights])

def loss_fn(y, y_hat, weights, biases, lamda):
	'''
	Compute loss =  loss_mse(..) + lamda * loss_regularization(..)
	Parameters
	----------
		y : targets, numpy array of shape m x 1
		y_hat : predictions, numpy array of shape m x 1
		weights and biases of the network
		lamda: Regularization parameter
	Returns
	----------
		l2 regularization loss 
	'''
	return loss_mse(y, y_hat) + lamda * loss_regularization(weights, biases)

def rmse(y, y_hat):
	'''
	Compute Root Mean Squared Error (RMSE) loss betwee ground-truth and predicted values.
	Parameters
	----------
		y : targets, numpy array of shape m x 1
		y_hat : predictions, numpy array of shape m x 1
	Returns
	----------
		RMSE between y and y_hat.
	'''
	return np.sqrt(loss_mse(y, y_hat))

def cross_entropy_loss(y, y_hat):
	'''
	Compute cross entropy loss
	Parameters
	----------
		y : targets, numpy array of shape m x 1
		y_hat : predictions, numpy array of shape m x 1
	Returns
	----------
		cross entropy loss
	'''

	return -1 * np.sum(y*np.log(y_hat))

def train(
	net, optimizer, lamda, batch_size, max_epochs,
	train_input, train_target,
	dev_input, dev_target
):
	'''
	In this function, you will perform following steps:
		1. Run gradient descent algorithm for `max_epochs` epochs.
		2. For each bach of the training data
			1.1 Compute gradients
			1.2 Update weights and biases using step() of optimizer.
		3. Compute RMSE on dev data after running `max_epochs` epochs.
	Here we have added the code to loop over batches and perform backward pass
	for each batch in the loop.
	For this code also, you are free to heavily modify it.
	'''

	m = train_input.shape[0]

	train_losses = []
	dev_losses = []

	for e in range(max_epochs):
		epoch_loss = 0.
		for i in range(0, m, batch_size):
			batch_input = train_input[i:i+batch_size]
			batch_target = train_target[i:i+batch_size]
			pred = net(batch_input)
			
			# Compute gradients of loss w.r.t. weights and biases
			dW, db = net.backward(batch_input, batch_target, lamda)

			# Get updated weights based on current weights and gradients
			weights_updated, biases_updated = optimizer.step(net.weights, net.biases, dW, db)

			# Update model's weights and biases
			net.weights = weights_updated
			net.biases = biases_updated

			# Compute loss for the batch
			batch_loss = loss_fn(batch_target, pred, net.weights, net.biases, lamda)
			epoch_loss += batch_loss
			
			#print(e, i, rmse(batch_target, pred), batch_loss)

		#print(e, epoch_loss)
		train_losses.append(loss_mse(train_target, net(train_input)))
		dev_losses.append(rmse(dev_target, net(dev_input)))
		# Write any early stopping conditions required (only for Part 2)
		# Hint: You can also compute dev_rmse here and use it in the early
		# 		stopping condition.

	# After running `max_epochs` (for Part 1) epochs OR early stopping (for Part 2), compute the RMSE on dev data.
	dev_pred = net(dev_input)
	dev_rmse = rmse(dev_target, dev_pred)
 	
	print('RMSE on dev data: {:.5f}'.format(dev_rmse))
	return train_losses, dev_losses

def get_test_data_predictions(net, inputs):
	'''
	Perform forward pass on test data and get the final predictions that can
	be submitted on Kaggle.
	Write the final predictions to the part2.csv file.
	Parameters
	----------
		net : trained neural network
		inputs : test input, numpy array of shape m x d
	Returns
	----------
		predictions (optional): Predictions obtained from forward pass
								on test data, numpy array of shape m x 1
	'''
	predictions = net(inputs)
	import csv
	filename = "part2.csv"

	with open(filename, 'w') as csvfile: 
		csvwriter = csv.writer(csvfile)
		csvwriter.writerow(("Id", "Predictions"))
		for i, j in enumerate(predictions[0]):
			csvwriter.writerow((i+1, j))
	return predictions

def read_data():
    dev = pd.read_csv('22m0794/regression/data/dev.csv')
    train = pd.read_csv('22m0794/regression/data/train.csv')
    test = pd.read_csv('22m0794/regression/data/test.csv')
    
    train_target = np.array(train.iloc[:,0])
    dev_target = np.array(dev.iloc[:,0])

    train_input = np.array(train.iloc[:, 1:])
    dev_input = np.array(dev.iloc[:, 1:])
    test_input = np.array(test)


    train_input = (train_input - train_input.mean(axis = 0)) / train_input.std(axis = 0)
    dev_input = (dev_input - dev_input.mean(axis = 0)) / dev_input.std(axis = 0)
    test_input = (test_input - test_input.mean(axis = 0)) / test_input.std(axis = 0)

    return train_input, train_target, dev_input, dev_target, test_input

def main():

	# Hyper-parameters 
	max_epochs = 100
	batch_size = 32
	learning_rate = 0.01
	num_layers = 2

	num_units =  64
	lamda = 0.1 # Regularization Parameter

	train_input, train_target, dev_input, dev_target, test_input = read_data()
	net = Net(num_layers, num_units)
	optimizer = Optimizer(learning_rate, net.weights, net.biases)
	train_losses, dev_losses = train(
					net, optimizer, lamda, batch_size, max_epochs,
					train_input, train_target,
					dev_input, dev_target
				)
	get_test_data_predictions(net, test_input)

if __name__ == '__main__':
	main()





